### ISSUE TITLE
Answer Acknowledgement (Sizzle)

### ISSUE THREAD

**Issue by lindsaymacvean** [Scholar-6/learning-fortress-frontend#197]

**Comment by aromakh** [comment]
@lindsaymacvean Could you please specify more details?

**Comment by lindsaymacvean** [comment]
I think we should add some of these effects to the all the progression buttons

https://tympanus.net/Development/Animocons/

**Comment by lindsaymacvean** [comment]
Lets apply number 14 effect to the next button

![image](https://user-images.githubusercontent.com/1574178/48415584-b29a0c80-e745-11e8-9b88-3db8e6e9fd87.png)

![image](https://user-images.githubusercontent.com/1574178/48415615-c6457300-e745-11e8-8cb2-41191fd53a13.png)
This is on /intro /live etc

The original github readme is here
https://github.com/legomushroom/mojs

**Comment by aromakh** [comment]
@lindsaymacvean Hi,
I think this compatible with angular becouse ower commented that he used it with angular.
But it can be hard to implement.
I think we will need to create some component for it, because it is 1200 lines of code.

**Comment by lindsaymacvean** [comment]
I feel we should look at easier options for angular.

**Comment by aromakh** [comment]
Find another library but didn`t find for angular.
https://tympanus.net/Development/ParticleEffectsButtons/

**Comment by aromakh** [comment]
@lindsaymacvean Hi,
I see that connecting mojs is n`t so hard.
Which of that animations you wanna to add for button in review page?
There is 10 of them you can just tell number.

**Comment by aromakh** [comment]
Added first of them 
![image](https://user-images.githubusercontent.com/7169477/48500109-b65f8900-e842-11e8-9045-2f89cd814864.png)

**Comment by lindsaymacvean** [comment]
Working on live. I am still looking for other effects to make it better.
