### ISSUE TITLE
New Component: dropdown select a word

### ISSUE THREAD

**Issue by lindsaymacvean** [Scholar-6/learning-fortress-frontend#198]
![image](https://user-images.githubusercontent.com/1574178/47793206-ac536b80-dd15-11e8-98b0-849a844ff4f5.png)

Create a component that has empty spaces that are dropdowns so that they user can select the right word.

**Comment by aromakh** [comment]
@lindsaymacvean Could you please specify more details?

**Comment by lindsaymacvean** [comment]
This is probably dependent on #200 because I need to test the review app against the dev firebase.

**Comment by aromakh** [comment]
@lindsaymacvean Hi.
As I see all components are setting up in this file: https://github.com/Scholar-6/learning-fortress-frontend/blob/dev/src/app/build/brick/comp/comp_index.ts#L14
And then just using here as dynamic components with data: https://github.com/Scholar-6/learning-fortress-frontend/blob/dev/src/app/build/brick/question.component.ts#L12

I will:
1. Update dev firestore with new brick TextDropdowns with new question TextDropdowns.
2. Create new angular component for this question.
3. Register component in comp_index.ts by register() function.
4. Then update brick art history, only first question.

**Comment by lindsaymacvean** [comment]
Do everything by number 4. I will do that myself.

**Comment by aromakh** [comment]
It will looks like this
![image](https://user-images.githubusercontent.com/7169477/47860621-9fa84380-ddf9-11e8-9b09-86ec352562c7.png)

**Comment by lindsaymacvean** [comment]
Great please create a pull request and create an example in the dev firestore that I can copy to production.

**Comment by aromakh** [comment]
@lindsaymacvean created in dev https://console.firebase.google.com/u/1/project/learning-fortress-dev/database/firestore/data~2Fbricks~2FTextDropdowns

**Comment by world-wanted** [comment]
I don't think this is needed.

**Comment by lindsaymacvean** [comment]
This seems to be working well on v44
