### ISSUE TITLE
Alter Timing on Drag and Drop

### ISSUE THREAD

**Issue by lindsaymacvean** [Scholar-6/learning-fortress-frontend#208]
On the Arrow Sort and Order components the drag and drop is still a little user unfriendly on mobiles.

1. When the user puts his finger on a dragable element they expect it to respond by shifting slightly to show it is being selected
2. If the user waits longer than about 500ms the element will not be dragged (to put it another way the user has to immediately move their finger in order to drag the element)

We should fix this by creating a slight shift effect when the finger is placed on the element and we should extend the time during which the element is draggable after the finger is placed on the element and not moved.

**Comment by lindsaymacvean** [comment]
@aromakh we need to discuss this on the phone. And see if we can come up with a solution.

**Comment by lindsaymacvean** [comment]
I am considering if we need to look at another library. This is a big job but I want to get this drag and drop right. 

It needs to work effortlessly on mobile (including IOS6)

**Comment by aromakh** [comment]
As, I see html haven`t default drag and drop for Phones only for PC.
There is many altirnatives for dragula I will check them:
https://www.producthunt.com/alternatives/dragula

**Comment by aromakh** [comment]
Add new drag and drop feature in Arrow component from material which needs angular/cdk 7.0.3.

**Comment by lindsaymacvean** [comment]
We solved this just for Arrow component and will fix the others in #262
