### ISSUE TITLE
The numbers are slightly cut off on mobile view

### ISSUE THREAD

**Issue by lindsaymacvean** [Scholar-6/learning-fortress-frontend#209]
When viewing the app on mobile the numbers at the top of the /live and /review phase appear slightly cut off on the right hand side. 

![whatsapp image 2018-10-29 at 08 53 06](https://user-images.githubusercontent.com/1574178/47639028-32c24e80-db58-11e8-9d1c-91cbe60187e7.jpeg)

**Comment by aromakh** [comment]
Fixed
![image](https://user-images.githubusercontent.com/7169477/47722522-460a1280-dc5b-11e8-83c5-388ad19daee7.png)
