### ISSUE TITLE
Left Justify text in executive summary on mobile view

### ISSUE THREAD

**Issue by lindsaymacvean** [Scholar-6/learning-fortress-frontend#216]
On mobile view the executive summary text is center aligned. It should be left justified.

![image](https://user-images.githubusercontent.com/1574178/47706759-fa874280-dc21-11e8-9924-6aad0a67599c.png)

There should be some slight padding between the left side of the screen and the text, between 2-5px.

**Comment by aromakh** [comment]
just justify

**Comment by lindsaymacvean** [comment]
Resolved in v44 on live.
