### ISSUE TITLE
Icons cut off on mobile view

### ISSUE THREAD

**Issue by lindsaymacvean** [Scholar-6/learning-fortress-frontend#219]
On the mobile view the number icons are cut off on the right.
![image](https://user-images.githubusercontent.com/1574178/47707482-d88ebf80-dc23-11e8-92e7-270aa665bf42.png)

**Comment by HarryOsborne** [comment]
Duplicate #209

**Comment by lindsaymacvean** [comment]
I think we should remove the separators and put a line under the scroll area. 

This is creeping the task so maybe create a new one but I think we should have an arrow button to scroll the scroller sideways.

**Comment by lindsaymacvean** [comment]
@aromakh  can you remove the little grey line separating the numbers

![image](https://user-images.githubusercontent.com/1574178/47891565-a3fd4c80-de4b-11e8-96b4-240d1b3044cd.png)

**Comment by aromakh** [comment]
It will look like this.
![image](https://user-images.githubusercontent.com/7169477/47985769-6b77a000-e0e3-11e8-81e7-23d30d99f4eb.png)

**Comment by lindsaymacvean** [comment]
@aromakh  looks good.

**Comment by aromakh** [comment]
Added buttons to scrolling. Overflow: auto; - hide scroll when no needed
![image](https://user-images.githubusercontent.com/7169477/48012070-d9df5100-e129-11e8-8556-7a82dab3f04b.png)

**Comment by lindsaymacvean** [comment]
This seems to be working well in v44. We will implement the buttons in #247
