### ISSUE TITLE
Allow formatting on TextHighlighting

### ISSUE THREAD

**Issue by lindsaymacvean** [Scholar-6/learning-fortress-frontend#227]
![image](https://user-images.githubusercontent.com/1574178/47793877-2d5f3280-dd17-11e8-8e22-9a114961e1dc.png)

This may be challenging so don't spend too long before coming back to me with a report. 

Allow the text highlighting component to have formatting like `<br>` or `<p> `

**Comment by aromakh** [comment]
@lindsaymacvean 
![image](https://user-images.githubusercontent.com/7169477/47800594-45de4580-dd35-11e8-96e2-33427f14b5bb.png)
It works only for elements which not wrapping words like <br> and not working for <p> elements.
