### ISSUE TITLE
Create a little more padding Poem Component

### ISSUE THREAD

**Issue by lindsaymacvean** [Scholar-6/learning-fortress-frontend#241]
![image](https://user-images.githubusercontent.com/1574178/48037321-90abf300-e163-11e8-8f51-4f97f3a6ebeb.png)

I think we need about 10px more padding at the top of the poem component.

![image](https://user-images.githubusercontent.com/1574178/48037355-c7820900-e163-11e8-86fb-691b15245a28.png)

And about 40px more margin from the left hand side (or whatever is needed to make it feel more center aligned).

![image](https://user-images.githubusercontent.com/1574178/48037529-92c28180-e164-11e8-8816-2ba8c79c6530.png)

And give it a light grey background #e1e1e1

**Comment by aromakh** [comment]
@lindsaymacvean I can make it look like this (the first part of poem):
![image](https://user-images.githubusercontent.com/7169477/48218000-866f3c00-e391-11e8-9973-aeb8f7c35e12.png)


Or move left?

**Comment by lindsaymacvean** [comment]
Rolled out to live in v44
