### ISSUE TITLE
Change crosses and ticks to custom icons by Stan

### ISSUE THREAD

**Issue by william-gooch** [Scholar-6/learning-fortress-frontend#26]
Please make sure to do this on /review

**Comment by lindsaymacvean** [comment]
We need the logos from stan

**Comment by lindsaymacvean** [comment]
This is the svg that needs to be converted into font.

https://drive.google.com/file/d/1ScUhr-ngcYZbCtSWRSTd5gIxoYUxcd10/view?usp=sharing

**Comment by lindsaymacvean** [comment]
Change these 
![image](https://user-images.githubusercontent.com/1574178/47134238-ec413a00-d2a3-11e8-8613-329385afe2da.png)

![image](https://user-images.githubusercontent.com/1574178/47134254-f4997500-d2a3-11e8-8e6c-3cfe853d46bf.png)

Switch for the far left blue with solid background
![image](https://user-images.githubusercontent.com/1574178/47134307-198de800-d2a4-11e8-9557-ca2edb865a01.png)

**Comment by aromakh** [comment]
@lindsaymacvean  Could you please specify which crosses should be used for each place.

**Comment by lindsaymacvean** [comment]
We need to also do this for SingleChoice MultipleChoice and ShortAnswer

**Comment by lindsaymacvean** [comment]
This is working in v44
