### ISSUE TITLE
Roll out Animation to all buttons

### ISSUE THREAD

**Issue by lindsaymacvean** [Scholar-6/learning-fortress-frontend#272]
We have introduced mojs animation on the live phase buttons. 

I would now like to make this happen on review as well.

**Comment by aromakh** [comment]
@lindsaymacvean Hi,
Made it.
Animation works only in /play route.
Upgrade animation to work every time user clicked button (removed checks for click).
Added animation to Last button in Live phrase.
Added animation to all next and finish button in Review page.

**Comment by lindsaymacvean** [comment]
Looking good.
