### ISSUE TITLE
html formatting in mat-select dropdown (TextDropdowns

### ISSUE THREAD

**Issue by lindsaymacvean** [Scholar-6/learning-fortress-frontend#277]
When I insert HTML as an option in the dropdown and then select it as an answer in the question, the html does not render. 

![image](https://user-images.githubusercontent.com/1574178/48670600-fa3be200-eb11-11e8-9bf5-3105090f752e.png)

**Comment by aromakh** [comment]
@lindsaymacvean fixed:)

**Comment by lindsaymacvean** [comment]
Thankyou. Created a new task #287  for when the option is selected.
