### ISSUE TITLE
Render dropdown html when selected

### ISSUE THREAD

**Issue by lindsaymacvean** [Scholar-6/learning-fortress-frontend#287]
When the dropdown option with HTML has been selected it seems to strip out the HTML. 

![image](https://user-images.githubusercontent.com/1574178/48877074-6d3aa680-edf9-11e8-92d9-3fc473a5cf59.png)

I think there is a way to do this with selecttrigger 
https://material.angular.io/components/select/api#MatSelectTrigger

**Comment by aromakh** [comment]
@lindsaymacvean You are right. I added mat-select-trigger to mat-select. Now it displays HTML.
![image](https://user-images.githubusercontent.com/7169477/49002685-f25eec00-f168-11e8-8a83-dfd937469013.png)

**Comment by lindsaymacvean** [comment]
Merged and working on live.
