### ISSUE TITLE
Make Done button the same as next button

### ISSUE THREAD

**Issue by lindsaymacvean** [Scholar-6/learning-fortress-frontend#31]
![image](https://user-images.githubusercontent.com/1574178/44471161-3cdd4380-a623-11e8-80cf-ea9706ed43ff.png)

![image](https://user-images.githubusercontent.com/1574178/44471194-4d8db980-a623-11e8-9b02-8ae5563ed773.png)

**Comment by william-gooch** [comment]
Already done.
