### ISSUE TITLE
Insert browser warning for older browsers

### ISSUE THREAD

**Issue by lindsaymacvean** [Scholar-6/learning-fortress-frontend#41]
For browsers older than

Chrome 67
FF 61
IE 11
Android 6.0 Marshmallow
iOS 7.1.2 (Iphone 4)

We should probably handle this in node and it should be the most simple html page with the following message. 

"It looks like you are using an older browser, try downloading the latest Chrome or Firefox and come back"

Design should be using the same blue we have already used as background, and the logo in the middle at the top. 

Testing, we should use a chrome extension to change the user agent.

**Comment by aromakh** [comment]
Chrome extention to switch user-agent version https://chrome.google.com/webstore/detail/user-agent-switcher-for-g/ffhkkpnppgnfaobgihpdblnhmmbodake/related

**Comment by lindsaymacvean** [comment]
Im getting white screen on IE
https://www.browserling.com/browse/win/vista/ie/9/https%3A%2F%2Flearningfortress.scholar6.org
If it hits the free tier limit try a tor browser and that will get you going again.

I can't think what is happening.

**Comment by aromakh** [comment]
@lindsaymacvean Hi,
Problem is in server side.
In middleware: https://github.com/Scholar-6/learning-fortress-frontend/blob/dev/server.js#L15
When server render libs. I think middleware crashed during rendering to old browsers or browser crashed when getting libs.
I will search how to fix it.

**Comment by aromakh** [comment]
This not working only for root path like http://localhost:8080
For other routes  middleware works good and rendering files after gets request.

**Comment by aromakh** [comment]
@lindsaymacvean Hi,
Added middleware to check browser version before loading static files from `/dist`.

**Comment by lindsaymacvean** [comment]
Rolled out to live in v44

Interestingly, the final bug on this above may be the reason it wasnt working on older browsers to begin with, so we may have to revisit the number of modern browsers allowed.
