### ISSUE TITLE
Alter Countdown

### ISSUE THREAD

**Issue by lindsaymacvean** [Scholar-6/learning-fortress-frontend#61]
1. On all countdowns, remove the 'seconds' and leave just a number

2. For the following countdowns
For Live investigation /live
And Live review /review
It should be in RED #E30000 and progress automatically to the next stage (I think this already happens) when reach 0 on these phases

![image](https://user-images.githubusercontent.com/1574178/47387664-edd98a80-d707-11e8-9149-ddd7f7f2f945.png)

**Comment by aromakh** [comment]
Removed seconds and setted red text. It is already moving automatically to the next phase.
