### ISSUE TITLE
Make live review horizontal 

### ISSUE THREAD

**Issue by lindsaymacvean** [Scholar-6/learning-fortress-frontend#86]
Currently on the dev branch that is pending release.
On the live phase of the brick the questions are along the top like this
![image](https://user-images.githubusercontent.com/1574178/45786178-2ef10180-bc67-11e8-9e35-923c994ed385.png)

But if you click twice on the blue button you get to the 'review' phase and it is vertical.
![image](https://user-images.githubusercontent.com/1574178/45786213-5942bf00-bc67-11e8-9521-57ef9234b0b3.png)

We need to change the 'review phase' to be horizontal instead.

**Comment by world-wanted** [comment]
I modified this one as per your needs.
![screencapture-localhost-4200-play-brick-milton-live-2018-09-27-08_29_32 1](https://user-images.githubusercontent.com/19157725/46242795-c60e3580-c39a-11e8-99cc-d2b669780ba2.png)

**Comment by lindsaymacvean** [comment]
@aromakh  I have realised that we need to make live to also have numbers instead of question marks. Please change this and I will merge.

**Comment by lindsaymacvean** [comment]
First fix went in for this I think I might need to create a new task to resolve styling. Closing this one.
