### ISSUE TITLE
Change card icons to stans numbers

### ISSUE THREAD

**Issue by lindsaymacvean** [Scholar-6/learning-fortress-frontend#94]
Please make sure to do this on both /live and /summary

**Comment by lindsaymacvean** [comment]
The numbers seem slightly off on the dev site
![image](https://user-images.githubusercontent.com/1574178/47296709-07e17300-d60b-11e8-83a9-9e976a0833b5.png)

https://learning-fortress-frontend-dev.herokuapp.com/play/brick/art_history/live

I think this might have been from when I was merging back code from master and overwrote some styling.

**Comment by aromakh** [comment]
@lindsaymacvean  already fixed.
