### ISSUE TITLE
Add https cert to learningfortress.scholar6.org

### ISSUE THREAD

**Issue by lindsaymacvean** [Scholar-6/learning-fortress-frontend#98]

**Comment by lindsaymacvean** [comment]
Follow these instructions
https://help.heroku.com/J2R1S4T8/can-heroku-force-an-application-to-use-ssl-tls

When deployed http://learningfortress.scholar6.org should redirect to https://learningfortress.scholar6.org

**Comment by aromakh** [comment]
Added express-sslify in node js https://demo-ng-app.herokuapp.com/
